export const languages = [
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/af.png',
        localized_name: 'Afrikaans',
        key: 'af',
        flag_image_2x: 'http://api.itranslateapp.com/flags/af-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'af',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/sq.png',
        localized_name: 'Albanian',
        key: 'sq',
        flag_image_2x: 'http://api.itranslateapp.com/flags/sq-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'sq',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.arasau.nuancemobility.net',
        asr: 'ar_sa',
        flag_image_1x: 'http://api.itranslateapp.com/flags/ar-SA.png',
        localized_name: 'Arabic (Saudi)',
        key: 'ar-SA',
        flag_image_2x: 'http://api.itranslateapp.com/flags/ar-SA-2x.png',
        tts: { male: 'arabicmale', female: '' },
        tts_offline: { male: 'ar-SA', female: '' },
      },
      {
        asr_host: 'bm.nvc.araegy.nuancemobility.net',
        asr: 'ar_ae',
        flag_image_1x: 'http://api.itranslateapp.com/flags/ar-AE.png',
        localized_name: 'Arabic (UAE)',
        key: 'ar-AE',
        flag_image_2x: 'http://api.itranslateapp.com/flags/ar-AE-2x.png',
        tts: { male: 'arabicmale', female: '' },
        tts_offline: { male: 'ar-SA', female: '' },
      },
      {
        asr_host: 'bm.nvc.araare.nuancemobility.net',
        asr: 'ar_eg',
        flag_image_1x: 'http://api.itranslateapp.com/flags/ar-EG.png',
        localized_name: 'Arabic (Egypt)',
        key: 'ar-EG',
        flag_image_2x: 'http://api.itranslateapp.com/flags/ar-EG-2x.png',
        tts: { male: 'arabicmale', female: '' },
        tts_offline: { male: 'ar-SA', female: '' },
      },
    ],
    key: 'ar',
    text_alignment: 'right',
    transliteration: true,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/hy.png',
        localized_name: 'Armenian',
        key: 'hy',
        flag_image_2x: 'http://api.itranslateapp.com/flags/hy-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'hy',
    text_alignment: 'left',
    transliteration: true,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/az.png',
        localized_name: 'Azerbaijani',
        key: 'az',
        flag_image_2x: 'http://api.itranslateapp.com/flags/az-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'az',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/eu.png',
        localized_name: 'Basque',
        key: 'eu',
        flag_image_2x: 'http://api.itranslateapp.com/flags/eu-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'eu',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/be.png',
        localized_name: 'Belarusian',
        key: 'be',
        flag_image_2x: 'http://api.itranslateapp.com/flags/be-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'be',
    text_alignment: 'left',
    transliteration: true,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/bn.png',
        localized_name: 'Bengali',
        key: 'bn',
        flag_image_2x: 'http://api.itranslateapp.com/flags/bn-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'bn',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/bs.png',
        localized_name: 'Bosnian',
        key: 'bs',
        flag_image_2x: 'http://api.itranslateapp.com/flags/bs-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'bs',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/bg.png',
        localized_name: 'Bulgarian',
        key: 'bg',
        flag_image_2x: 'http://api.itranslateapp.com/flags/bg-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'bg',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.enGB.nuancemobility.net',
        asr: 'ca_es',
        flag_image_1x: 'http://api.itranslateapp.com/flags/ca.png',
        localized_name: 'Catalan',
        key: 'ca',
        flag_image_2x: 'http://api.itranslateapp.com/flags/ca-2x.png',
        tts: { male: '', female: 'eurcatalanfemale' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'ca',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/ceb.png',
        localized_name: 'Cebuano',
        key: 'ceb',
        flag_image_2x: 'http://api.itranslateapp.com/flags/ceb-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'ceb',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/ny.png',
        localized_name: 'Chichewa',
        key: 'ny',
        flag_image_2x: 'http://api.itranslateapp.com/flags/ny-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'ny',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.chMN.nuancemobility.net',
        asr: 'cn_ma',
        flag_image_1x: 'http://api.itranslateapp.com/flags/zh-CN.png',
        localized_name: 'Chinese (Mandarin)',
        key: 'zh-CN',
        flag_image_2x: 'http://api.itranslateapp.com/flags/zh-CN-2x.png',
        tts: { male: 'chchinesemale', female: 'chchinesefemale' },
        tts_offline: { male: '', female: 'zh-CN' },
      },
    ],
    key: 'zh-CN',
    text_alignment: 'left',
    transliteration: true,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.twMN.nuancemobility.net',
        asr: 'cmn-TWN',
        flag_image_1x: 'http://api.itranslateapp.com/flags/zh-TW.png',
        localized_name: 'Chinese (Taiwan)',
        key: 'zh-TW',
        flag_image_2x: 'http://api.itranslateapp.com/flags/zh-TW-2x.png',
        tts: { male: '', female: 'twchinesefemale' },
        tts_offline: { male: '', female: 'zh-TW' },
      },
      {
        asr_host: 'bm.nvc.chCN.nuancemobility.net',
        asr: 'zh_hk',
        flag_image_1x: 'http://api.itranslateapp.com/flags/zh-HK.png',
        localized_name: 'Chinese (Cantonese)',
        key: 'zh-HK',
        flag_image_2x: 'http://api.itranslateapp.com/flags/zh-HK-2x.png',
        tts: { male: '', female: 'hkchinesefemale' },
        tts_offline: { male: '', female: 'zh-HK' },
      },
    ],
    key: 'zh-TW',
    text_alignment: 'left',
    transliteration: true,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.enGB.nuancemobility.net',
        asr: 'hr_hr',
        flag_image_1x: 'http://api.itranslateapp.com/flags/hr.png',
        localized_name: 'Croatian',
        key: 'hr',
        flag_image_2x: 'http://api.itranslateapp.com/flags/hr-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'hr',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.cscz.nuancemobility.net',
        asr: 'cs_cz',
        flag_image_1x: 'http://api.itranslateapp.com/flags/cs.png',
        localized_name: 'Czech',
        key: 'cs',
        flag_image_2x: 'http://api.itranslateapp.com/flags/cs-2x.png',
        tts: { male: '', female: 'eurczechfemale' },
        tts_offline: { male: '', female: 'cs-CZ' },
      },
    ],
    key: 'cs',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.dandan.nuancemobility.net',
        asr: 'da_dk',
        flag_image_1x: 'http://api.itranslateapp.com/flags/da.png',
        localized_name: 'Danish',
        key: 'da',
        flag_image_2x: 'http://api.itranslateapp.com/flags/da-2x.png',
        tts: { male: '', female: 'eurdanishfemale' },
        tts_offline: { male: '', female: 'da-DK' },
      },
    ],
    key: 'da',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/auto.png',
        localized_name: 'Detect Language',
        key: 'auto',
        flag_image_2x: 'http://api.itranslateapp.com/flags/auto-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'auto',
    text_alignment: '',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.nldnld.nuancemobility.net',
        asr: 'nl_nl',
        flag_image_1x: 'http://api.itranslateapp.com/flags/nl.png',
        localized_name: 'Dutch',
        key: 'nl',
        flag_image_2x: 'http://api.itranslateapp.com/flags/nl-2x.png',
        tts: { male: 'Xander', female: 'eurdutchfemale' },
        tts_offline: { male: 'nl-NL', female: '' },
      },
    ],
    key: 'nl',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: true,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.enGB.nuancemobility.net',
        asr: 'en_gb',
        flag_image_1x: 'http://api.itranslateapp.com/flags/en-UK.png',
        localized_name: 'English (GB)',
        key: 'en-UK',
        flag_image_2x: 'http://api.itranslateapp.com/flags/en-UK-2x.png',
        tts: { male: 'ukenglishmale', female: 'ukenglishfemale' },
        tts_offline: { male: 'en-GB', female: '' },
      },
      {
        asr_host: 'bm.nvc.enUS.nuancemobility.net',
        asr: 'en_us',
        flag_image_1x: 'http://api.itranslateapp.com/flags/en-US.png',
        localized_name: 'English (USA)',
        key: 'en-US',
        flag_image_2x: 'http://api.itranslateapp.com/flags/en-US-2x.png',
        tts: { male: 'usenglishmale', female: 'usenglishfemale' },
        tts_offline: { male: '', female: 'en-US' },
      },
      {
        asr_host: 'bm.nvc.enAU.nuancemobility.net',
        asr: 'en_au',
        flag_image_1x: 'http://api.itranslateapp.com/flags/en-AU.png',
        localized_name: 'English (Australia)',
        key: 'en-AU',
        flag_image_2x: 'http://api.itranslateapp.com/flags/en-AU-2x.png',
        tts: { male: 'Lee', female: 'auenglishfemale' },
        tts_offline: { male: '', female: 'en-AU' },
      },
    ],
    key: 'en',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: true,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/eo.png',
        localized_name: 'Esperanto',
        key: 'eo',
        flag_image_2x: 'http://api.itranslateapp.com/flags/eo-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'eo',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/et.png',
        localized_name: 'Estonian',
        key: 'et',
        flag_image_2x: 'http://api.itranslateapp.com/flags/et-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'et',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/tl.png',
        localized_name: 'Filipino',
        key: 'tl',
        flag_image_2x: 'http://api.itranslateapp.com/flags/tl-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'tl',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.fifi.nuancemobility.net',
        asr: 'fi_fi',
        flag_image_1x: 'http://api.itranslateapp.com/flags/fi.png',
        localized_name: 'Finnish',
        key: 'fi',
        flag_image_2x: 'http://api.itranslateapp.com/flags/fi-2x.png',
        tts: { male: '', female: 'eurfinnishfemale' },
        tts_offline: { male: '', female: 'fi-FI' },
      },
    ],
    key: 'fi',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.frfr.nuancemobility.net',
        asr: 'fr_fr',
        flag_image_1x: 'http://api.itranslateapp.com/flags/fr-FR.png',
        localized_name: 'French',
        key: 'fr-FR',
        flag_image_2x: 'http://api.itranslateapp.com/flags/fr-FR-2x.png',
        tts: { male: 'eurfrenchmale', female: 'eurfrenchfemale' },
        tts_offline: { male: 'fr-FR', female: '' },
      },
      {
        asr_host: 'bm.nvc.frCA.nuancemobility.net',
        asr: 'fr_ca',
        flag_image_1x: 'http://api.itranslateapp.com/flags/fr-CA.png',
        localized_name: 'French (Canada)',
        key: 'fr-CA',
        flag_image_2x: 'http://api.itranslateapp.com/flags/fr-CA-2x.png',
        tts: { male: 'cafrenchmale', female: 'cafrenchfemale' },
        tts_offline: { male: '', female: 'fr-CA' },
      },
    ],
    key: 'fr',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: true,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/gl.png',
        localized_name: 'Galician',
        key: 'gl',
        flag_image_2x: 'http://api.itranslateapp.com/flags/gl-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'gl',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/ka.png',
        localized_name: 'Georgian',
        key: 'ka',
        flag_image_2x: 'http://api.itranslateapp.com/flags/ka-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'ka',
    text_alignment: 'left',
    transliteration: true,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.dede.nuancemobility.net',
        asr: 'de_de',
        flag_image_1x: 'http://api.itranslateapp.com/flags/de.png',
        localized_name: 'German',
        key: 'de',
        flag_image_2x: 'http://api.itranslateapp.com/flags/de-2x.png',
        tts: { male: 'eurgermanmale', female: 'eurgermanfemale' },
        tts_offline: { male: '', female: 'de-DE' },
      },
    ],
    key: 'de',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: true,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.elgr.nuancemobility.net',
        asr: 'el_gr',
        flag_image_1x: 'http://api.itranslateapp.com/flags/el.png',
        localized_name: 'Greek',
        key: 'el',
        flag_image_2x: 'http://api.itranslateapp.com/flags/el-2x.png',
        tts: { male: 'Alexandros', female: 'eurgreekfemale' },
        tts_offline: { male: '', female: 'el-GR' },
      },
    ],
    key: 'el',
    text_alignment: 'left',
    transliteration: true,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/gu.png',
        localized_name: 'Gujarati',
        key: 'gu',
        flag_image_2x: 'http://api.itranslateapp.com/flags/gu-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'gu',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/ht.png',
        localized_name: 'Haitian Creole',
        key: 'ht',
        flag_image_2x: 'http://api.itranslateapp.com/flags/ht-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'ht',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/ha.png',
        localized_name: 'Hausa',
        key: 'ha',
        flag_image_2x: 'http://api.itranslateapp.com/flags/ha-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'ha',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.enGB.nuancemobility.net',
        asr: 'he_il',
        flag_image_1x: 'http://api.itranslateapp.com/flags/iw.png',
        localized_name: 'Hebrew',
        key: 'iw',
        flag_image_2x: 'http://api.itranslateapp.com/flags/iw-2x.png',
        tts: { male: '', female: 'Carmit' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'iw',
    text_alignment: 'right',
    transliteration: true,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.enGB.nuancemobility.net',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/hi.png',
        localized_name: 'Hindi',
        key: 'hi',
        flag_image_2x: 'http://api.itranslateapp.com/flags/hi-2x.png',
        tts: { male: '', female: 'Lekha' },
        tts_offline: { male: '', female: 'hi-IN' },
      },
    ],
    key: 'hi',
    text_alignment: 'left',
    transliteration: true,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/hmn.png',
        localized_name: 'Hmong',
        key: 'hmn',
        flag_image_2x: 'http://api.itranslateapp.com/flags/hmn-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'hmn',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.huhu.nuancemobility.net',
        asr: 'hu_hu',
        flag_image_1x: 'http://api.itranslateapp.com/flags/hu.png',
        localized_name: 'Hungarian',
        key: 'hu',
        flag_image_2x: 'http://api.itranslateapp.com/flags/hu-2x.png',
        tts: { male: '', female: 'huhungarianfemale' },
        tts_offline: { male: '', female: 'hu-HU' },
      },
    ],
    key: 'hu',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/is.png',
        localized_name: 'Icelandic',
        key: 'is',
        flag_image_2x: 'http://api.itranslateapp.com/flags/is-2x.png',
        tts: { male: 'is-male', female: 'is-female' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'is',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/ig.png',
        localized_name: 'Igbo',
        key: 'ig',
        flag_image_2x: 'http://api.itranslateapp.com/flags/ig-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'ig',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.idid.nuancemobility.net',
        asr: 'id_id',
        flag_image_1x: 'http://api.itranslateapp.com/flags/id.png',
        localized_name: 'Indonesian',
        key: 'id',
        flag_image_2x: 'http://api.itranslateapp.com/flags/id-2x.png',
        tts: { male: '', female: 'Damayanti' },
        tts_offline: { male: '', female: 'id-ID' },
      },
    ],
    key: 'id',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/ga.png',
        localized_name: 'Irish',
        key: 'ga',
        flag_image_2x: 'http://api.itranslateapp.com/flags/ga-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'ga',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.itit.nuancemobility.net',
        asr: 'it_it',
        flag_image_1x: 'http://api.itranslateapp.com/flags/it.png',
        localized_name: 'Italian',
        key: 'it',
        flag_image_2x: 'http://api.itranslateapp.com/flags/it-2x.png',
        tts: { male: 'euritalianmale', female: 'euritalianfemale' },
        tts_offline: { male: '', female: 'it-IT' },
      },
    ],
    key: 'it',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: true,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.jpjp.nuancemobility.net',
        asr: 'ja_jp',
        flag_image_1x: 'http://api.itranslateapp.com/flags/ja.png',
        localized_name: 'Japanese',
        key: 'ja',
        flag_image_2x: 'http://api.itranslateapp.com/flags/ja-2x.png',
        tts: { male: 'jpjapanesemale', female: 'jpjapanesefemale' },
        tts_offline: { male: '', female: 'ja-JP' },
      },
    ],
    key: 'ja',
    text_alignment: 'left',
    transliteration: true,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/jw.png',
        localized_name: 'Javanese',
        key: 'jw',
        flag_image_2x: 'http://api.itranslateapp.com/flags/jw-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'jw',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/kn.png',
        localized_name: 'Kannada',
        key: 'kn',
        flag_image_2x: 'http://api.itranslateapp.com/flags/kn-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'kn',
    text_alignment: 'left',
    transliteration: true,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/kk.png',
        localized_name: 'Kazakh',
        key: 'kk',
        flag_image_2x: 'http://api.itranslateapp.com/flags/kk-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'kk',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/km.png',
        localized_name: 'Khmer',
        key: 'km',
        flag_image_2x: 'http://api.itranslateapp.com/flags/km-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'km',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.koko.nuancemobility.net',
        asr: 'ko_kr',
        flag_image_1x: 'http://api.itranslateapp.com/flags/ko.png',
        localized_name: 'Korean',
        key: 'ko',
        flag_image_2x: 'http://api.itranslateapp.com/flags/ko-2x.png',
        tts: { male: 'krkoreanmale', female: 'krkoreanfemale' },
        tts_offline: { male: '', female: 'ko-KR' },
      },
    ],
    key: 'ko',
    text_alignment: 'left',
    transliteration: true,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/lo.png',
        localized_name: 'Lao',
        key: 'lo',
        flag_image_2x: 'http://api.itranslateapp.com/flags/lo-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'lo',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/la.png',
        localized_name: 'Latin',
        key: 'la',
        flag_image_2x: 'http://api.itranslateapp.com/flags/la-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'la',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/lv.png',
        localized_name: 'Latvian',
        key: 'lv',
        flag_image_2x: 'http://api.itranslateapp.com/flags/lv-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'lv',
    text_alignment: 'left',
    transliteration: true,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/lt.png',
        localized_name: 'Lithuanian',
        key: 'lt',
        flag_image_2x: 'http://api.itranslateapp.com/flags/lt-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'lt',
    text_alignment: 'left',
    transliteration: true,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/mk.png',
        localized_name: 'Macedonian',
        key: 'mk',
        flag_image_2x: 'http://api.itranslateapp.com/flags/mk-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'mk',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/mg.png',
        localized_name: 'Malagasy',
        key: 'mg',
        flag_image_2x: 'http://api.itranslateapp.com/flags/mg-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'mg',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.msmy.nuancemobility.net',
        asr: 'ms_my',
        flag_image_1x: 'http://api.itranslateapp.com/flags/ms.png',
        localized_name: 'Malay',
        key: 'ms',
        flag_image_2x: 'http://api.itranslateapp.com/flags/ms-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'ms',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/ml.png',
        localized_name: 'Malayalam',
        key: 'ml',
        flag_image_2x: 'http://api.itranslateapp.com/flags/ml-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'ml',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/mt.png',
        localized_name: 'Maltese',
        key: 'mt',
        flag_image_2x: 'http://api.itranslateapp.com/flags/mt-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'mt',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/mi.png',
        localized_name: 'Maori',
        key: 'mi',
        flag_image_2x: 'http://api.itranslateapp.com/flags/mi-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'mi',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/mr.png',
        localized_name: 'Marathi',
        key: 'mr',
        flag_image_2x: 'http://api.itranslateapp.com/flags/mr-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'mr',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/mn.png',
        localized_name: 'Mongolian',
        key: 'mn',
        flag_image_2x: 'http://api.itranslateapp.com/flags/mn-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'mn',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/my.png',
        localized_name: 'Myanmar (Burmese)',
        key: 'my',
        flag_image_2x: 'http://api.itranslateapp.com/flags/my-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'my',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/ne.png',
        localized_name: 'Nepali',
        key: 'ne',
        flag_image_2x: 'http://api.itranslateapp.com/flags/ne-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'ne',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.nornor.nuancemobility.net',
        asr: 'no_no',
        flag_image_1x: 'http://api.itranslateapp.com/flags/no.png',
        localized_name: 'Norwegian',
        key: 'no',
        flag_image_2x: 'http://api.itranslateapp.com/flags/no-2x.png',
        tts: { male: '', female: 'eurnorwegianfemale' },
        tts_offline: { male: '', female: 'no-NO' },
      },
    ],
    key: 'no',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/fa.png',
        localized_name: 'Persian',
        key: 'fa',
        flag_image_2x: 'http://api.itranslateapp.com/flags/fa-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'fa',
    text_alignment: 'right',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.polpol.nuancemobility.net',
        asr: 'pl_pl',
        flag_image_1x: 'http://api.itranslateapp.com/flags/pl.png',
        localized_name: 'Polish',
        key: 'pl',
        flag_image_2x: 'http://api.itranslateapp.com/flags/pl-2x.png',
        tts: { male: '', female: 'eurpolishfemale' },
        tts_offline: { male: '', female: 'pl-PL' },
      },
    ],
    key: 'pl',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.porpor.nuancemobility.net',
        asr: 'pt_pt',
        flag_image_1x: 'http://api.itranslateapp.com/flags/pt-PT.png',
        localized_name: 'Portuguese (Portugal)',
        key: 'pt-PT',
        flag_image_2x: 'http://api.itranslateapp.com/flags/pt-PT-2x.png',
        tts: {
          male: 'eurportuguesemale',
          female: 'eurportuguesefemale',
        },
        tts_offline: { male: '', female: 'pt-PT' },
      },
      {
        asr_host: 'bm.nvc.porbra.nuancemobility.net',
        asr: 'pt_br',
        flag_image_1x: 'http://api.itranslateapp.com/flags/pt-BR.png',
        localized_name: 'Portuguese (Brazil)',
        key: 'pt-BR',
        flag_image_2x: 'http://api.itranslateapp.com/flags/pt-BR-2x.png',
        tts: { male: '', female: 'brportuguesefemale' },
        tts_offline: { male: '', female: 'pt-BR' },
      },
    ],
    key: 'pt',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: true,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/pa.png',
        localized_name: 'Punjabi',
        key: 'pa',
        flag_image_2x: 'http://api.itranslateapp.com/flags/pa-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'pa',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.roro.nuancemobility.net',
        asr: 'ro_ro',
        flag_image_1x: 'http://api.itranslateapp.com/flags/ro.png',
        localized_name: 'Romanian',
        key: 'ro',
        flag_image_2x: 'http://api.itranslateapp.com/flags/ro-2x.png',
        tts: { male: '', female: 'Simona' },
        tts_offline: { male: '', female: 'ro-RO' },
      },
    ],
    key: 'ro',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.rusrus.nuancemobility.net',
        asr: 'ru_ru',
        flag_image_1x: 'http://api.itranslateapp.com/flags/ru.png',
        localized_name: 'Russian',
        key: 'ru',
        flag_image_2x: 'http://api.itranslateapp.com/flags/ru-2x.png',
        tts: { male: 'rurussianmale', female: 'rurussianfemale' },
        tts_offline: { male: '', female: 'ru-RU' },
      },
    ],
    key: 'ru',
    text_alignment: 'left',
    transliteration: true,
    auto_completion: true,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/sr.png',
        localized_name: 'Serbian',
        key: 'sr',
        flag_image_2x: 'http://api.itranslateapp.com/flags/sr-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'sr',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/st.png',
        localized_name: 'Sesotho',
        key: 'st',
        flag_image_2x: 'http://api.itranslateapp.com/flags/st-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'st',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/si.png',
        localized_name: 'Sinhala',
        key: 'si',
        flag_image_2x: 'http://api.itranslateapp.com/flags/si-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'si',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.sksk.nuancemobility.net',
        asr: 'sk_sk',
        flag_image_1x: 'http://api.itranslateapp.com/flags/sk.png',
        localized_name: 'Slovak',
        key: 'sk',
        flag_image_2x: 'http://api.itranslateapp.com/flags/sk-2x.png',
        tts: { male: '', female: 'Laura' },
        tts_offline: { male: '', female: 'sk-SK' },
      },
    ],
    key: 'sk',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/sl.png',
        localized_name: 'Slovenian',
        key: 'sl',
        flag_image_2x: 'http://api.itranslateapp.com/flags/sl-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'sl',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/so.png',
        localized_name: 'Somali',
        key: 'so',
        flag_image_2x: 'http://api.itranslateapp.com/flags/so-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'so',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.eses.nuancemobility.net',
        asr: 'es_es',
        flag_image_1x: 'http://api.itranslateapp.com/flags/es-ES.png',
        localized_name: 'Spanish (Spain)',
        key: 'es-ES',
        flag_image_2x: 'http://api.itranslateapp.com/flags/es-ES-2x.png',
        tts: { male: 'eurspanishmale', female: 'eurspanishfemale' },
        tts_offline: { male: '', female: 'es-ES' },
      },
      {
        asr_host: 'bm.nvc.esUS.nuancemobility.net',
        asr: 'es_us',
        flag_image_1x: 'http://api.itranslateapp.com/flags/es-US.png',
        localized_name: 'Spanish (United States)',
        key: 'es-US',
        flag_image_2x: 'http://api.itranslateapp.com/flags/es-US-2x.png',
        tts: { male: 'usspanishmale', female: 'usspanishfemale' },
        tts_offline: { male: '', female: 'es-ES' },
      },
      {
        asr_host: 'bm.nvc.esMX.nuancemobility.net',
        asr: 'es_mx',
        flag_image_1x: 'http://api.itranslateapp.com/flags/es-MX.png',
        localized_name: 'Spanish (Mexico)',
        key: 'es-MX',
        flag_image_2x: 'http://api.itranslateapp.com/flags/es-MX-2x.png',
        tts: { male: 'usspanishmale', female: 'usspanishfemale' },
        tts_offline: { male: '', female: 'es-MX' },
      },
    ],
    key: 'es',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: true,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/su.png',
        localized_name: 'Sundanese',
        key: 'su',
        flag_image_2x: 'http://api.itranslateapp.com/flags/su-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'su',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/sw.png',
        localized_name: 'Swahili',
        key: 'sw',
        flag_image_2x: 'http://api.itranslateapp.com/flags/sw-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'sw',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.sweswe.nuancemobility.net',
        asr: 'sv_se',
        flag_image_1x: 'http://api.itranslateapp.com/flags/sv.png',
        localized_name: 'Swedish',
        key: 'sv',
        flag_image_2x: 'http://api.itranslateapp.com/flags/sv-2x.png',
        tts: { male: 'Oskar', female: 'swswedishfemale' },
        tts_offline: { male: '', female: 'sv-SE' },
      },
    ],
    key: 'sv',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: true,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/tg.png',
        localized_name: 'Tajik',
        key: 'tg',
        flag_image_2x: 'http://api.itranslateapp.com/flags/tg-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'tg',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/ta.png',
        localized_name: 'Tamil',
        key: 'ta',
        flag_image_2x: 'http://api.itranslateapp.com/flags/ta-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'ta',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/te.png',
        localized_name: 'Telugu',
        key: 'te',
        flag_image_2x: 'http://api.itranslateapp.com/flags/te-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'te',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.enGB.nuancemobility.net',
        asr: 'th_th',
        flag_image_1x: 'http://api.itranslateapp.com/flags/th.png',
        localized_name: 'Thai',
        key: 'th',
        flag_image_2x: 'http://api.itranslateapp.com/flags/th-2x.png',
        tts: { male: '', female: 'Narisa' },
        tts_offline: { male: '', female: 'th-TH' },
      },
    ],
    key: 'th',
    text_alignment: 'left',
    transliteration: true,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.trtr.nuancemobility.net',
        asr: 'tr_tr',
        flag_image_1x: 'http://api.itranslateapp.com/flags/tr.png',
        localized_name: 'Turkish',
        key: 'tr',
        flag_image_2x: 'http://api.itranslateapp.com/flags/tr-2x.png',
        tts: { male: 'eurturkishmale', female: 'eurturkishfemale' },
        tts_offline: { male: '', female: 'tr-TR' },
      },
    ],
    key: 'tr',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.enGB.nuancemobility.net',
        asr: 'uk_ua',
        flag_image_1x: 'http://api.itranslateapp.com/flags/uk.png',
        localized_name: 'Ukrainian',
        key: 'uk',
        flag_image_2x: 'http://api.itranslateapp.com/flags/uk-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'uk',
    text_alignment: 'left',
    transliteration: true,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/ur.png',
        localized_name: 'Urdu',
        key: 'ur',
        flag_image_2x: 'http://api.itranslateapp.com/flags/ur-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'ur',
    text_alignment: 'left',
    transliteration: true,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/uz.png',
        localized_name: 'Uzbek',
        key: 'uz',
        flag_image_2x: 'http://api.itranslateapp.com/flags/uz-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'uz',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: 'bm.nvc.vivn.nuancemobility.net',
        asr: 'vi_vn',
        flag_image_1x: 'http://api.itranslateapp.com/flags/vi.png',
        localized_name: 'Vietnamese',
        key: 'vi',
        flag_image_2x: 'http://api.itranslateapp.com/flags/vi-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'vi',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/cy.png',
        localized_name: 'Welsh',
        key: 'cy',
        flag_image_2x: 'http://api.itranslateapp.com/flags/cy-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'cy',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/yi.png',
        localized_name: 'Yiddish',
        key: 'yi',
        flag_image_2x: 'http://api.itranslateapp.com/flags/yi-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'yi',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/yo.png',
        localized_name: 'Yoruba',
        key: 'yo',
        flag_image_2x: 'http://api.itranslateapp.com/flags/yo-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'yo',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
  {
    dialects: [
      {
        asr_host: '',
        asr: '',
        flag_image_1x: 'http://api.itranslateapp.com/flags/zu.png',
        localized_name: 'Zulu',
        key: 'zu',
        flag_image_2x: 'http://api.itranslateapp.com/flags/zu-2x.png',
        tts: { male: '', female: '' },
        tts_offline: { male: '', female: '' },
      },
    ],
    key: 'zu',
    text_alignment: 'left',
    transliteration: false,
    auto_completion: false,
  },
];

const { dialects } = languages[0];
const language = dialects[0];

export type IDialects = typeof dialects;
export type ILanguage = typeof language;

export default {
  languages_count: 92,
  dialects_count: 101,
  languages,
};
